#!/usr/bin/env python3
import time

from SPARQLWrapper import JSON, SPARQLWrapper

from dictionaries.all import *
from helper import *
from login_info import *

sparqlwd = SPARQLWrapper(
    "https://query.wikidata.org/sparql",
    agent="numista2wikidata (https://github.com/lubianat/numista2wikidata)",
)

query = """
SELECT DISTINCT
  ?item ?numista_id
WHERE 
{
  ?item wdt:P10205 ?numista_id . 
} 
"""

sparqlwd.setQuery(query)
sparqlwd.setReturnFormat(JSON)
data = sparqlwd.query().convert()

current_ids = []
for result in data["results"]["bindings"]:
    current_ids.append(result["numista_id"]["value"])

endpoint = "https://api.numista.com/api/v2"
user_id = "231967"
response = requests.get(
    endpoint + "/users/" + user_id + "/collected_coins",
    params={"lang": "en"},
    headers={"Numista-API-Key": api_key},
)
user_details = response.json()

collected_coins = user_details["collected_coins"]

coin_ids = []
for coin in collected_coins:
    try:
        coin_ids.append(str(coin["coin"]["id"]))
    except:
        print(coin)
        break

coin_ids = list(set(coin_ids))

coin_statements = []
for coin_id in coin_ids:
    if coin_id not in current_ids:
        print("==================")
        print(f"./src/get_coin_info --coin_type_id {str(coin_id)}")
        print("==================")

        print(f"https://en.numista.com/catalogue/pieces{coin_id}.html")

        os.system(f"./src/get_coin_info --coin_type_id {str(coin_id)}")
        break
with open("new_coins.qs", "w") as f:
    f.write("\n".join(coin_statements))
